//
// This file is part of GyroidOS
// Copyright(c) 2013 - 2017 Fraunhofer AISEC
// Fraunhofer-Gesellschaft zur Förderung der angewandten Forschung e.V.
//
// This program is free software; you can redistribute it and/or modify it
// under the terms and conditions of the GNU General Public License,
// version 2 (GPL 2), as published by the Free Software Foundation.
//
// This program is distributed in the hope it will be useful, but WITHOUT
// ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
// FITNESS FOR A PARTICULAR PURPOSE. See the GPL 2 license for more details.
//
// You should have received a copy of the GNU General Public License along with
// this program; if not, see <http://www.gnu.org/licenses/>
//
// The full GNU General Public License is included in this distribution in
// the file called "COPYING".
//
// Contact Information:
// Fraunhofer AISEC <gyroidos@aisec.fraunhofer.de>

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.14.0
// source: logf.proto

package main

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LogMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name *string `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
	Msg  *string `protobuf:"bytes,2,req,name=msg" json:"msg,omitempty"`
}

func (x *LogMessage) Reset() {
	*x = LogMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_logf_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LogMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogMessage) ProtoMessage() {}

func (x *LogMessage) ProtoReflect() protoreflect.Message {
	mi := &file_logf_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogMessage.ProtoReflect.Descriptor instead.
func (*LogMessage) Descriptor() ([]byte, []int) {
	return file_logf_proto_rawDescGZIP(), []int{0}
}

func (x *LogMessage) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *LogMessage) GetMsg() string {
	if x != nil && x.Msg != nil {
		return *x.Msg
	}
	return ""
}

var File_logf_proto protoreflect.FileDescriptor

var file_logf_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x6c, 0x6f, 0x67, 0x66, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x6d, 0x61,
	0x69, 0x6e, 0x22, 0x32, 0x0a, 0x0a, 0x4c, 0x6f, 0x67, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x02, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x02, 0x28,
	0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x42, 0x24, 0x0a, 0x1b, 0x64, 0x65, 0x2e, 0x66, 0x72, 0x61,
	0x75, 0x6e, 0x68, 0x6f, 0x66, 0x65, 0x72, 0x2e, 0x61, 0x69, 0x73, 0x65, 0x63, 0x2e, 0x74, 0x72,
	0x75, 0x73, 0x74, 0x6d, 0x65, 0x5a, 0x05, 0x6d, 0x61, 0x69, 0x6e, 0x2f,
}

var (
	file_logf_proto_rawDescOnce sync.Once
	file_logf_proto_rawDescData = file_logf_proto_rawDesc
)

func file_logf_proto_rawDescGZIP() []byte {
	file_logf_proto_rawDescOnce.Do(func() {
		file_logf_proto_rawDescData = protoimpl.X.CompressGZIP(file_logf_proto_rawDescData)
	})
	return file_logf_proto_rawDescData
}

var file_logf_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_logf_proto_goTypes = []interface{}{
	(*LogMessage)(nil), // 0: main.LogMessage
}
var file_logf_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_logf_proto_init() }
func file_logf_proto_init() {
	if File_logf_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_logf_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LogMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_logf_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_logf_proto_goTypes,
		DependencyIndexes: file_logf_proto_depIdxs,
		MessageInfos:      file_logf_proto_msgTypes,
	}.Build()
	File_logf_proto = out.File
	file_logf_proto_rawDesc = nil
	file_logf_proto_goTypes = nil
	file_logf_proto_depIdxs = nil
}
